# Generated by Django 5.2.3 on 2025-06-20 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
