# Generated by Django 5.2.3 on 2025-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_id_remove_user_id_alter_item_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
