# Generated by Django 5.2.3 on 2025-06-28 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('closet_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(related_name='closets', to='api.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
