# Generated by Django 5.2.3 on 2025-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='added_to_cart',
            field=models.BooleanField(null=True),
        ),
    ]
