# Generated by Django 5.2.3 on 2025-08-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_brand_id_brand_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quant',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
