# Generated by Django 5.2.3 on 2025-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_item_brand_id_item_stock_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shadow',
            field=models.BooleanField(default=False),
        ),
    ]
