# Generated by Django 5.2.3 on 2025-09-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_itemvariant_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
