# Generated by Django 5.2.3 on 2025-10-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_cart_items_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
