# Generated by Django 5.2.3 on 2025-10-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cart_items_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='color',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
