# Generated by Django 5.2.3 on 2025-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_itemvariant_color_delete_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
