# Generated by Django 5.2.3 on 2025-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_seen_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.IntegerField(default=0),
        ),
    ]
