# Generated by Django 5.2.3 on 2025-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='user',
        ),
        migrations.AddField(
            model_name='closet',
            name='users',
            field=models.ManyToManyField(related_name='closets', to='api.user'),
        ),
    ]
