# Generated by Django 5.2.3 on 2025-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
