# Generated by Django 5.2.3 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_item_images_item_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
