# Generated by Django 5.2.3 on 2026-03-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_item_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
