# Generated by Django 5.2.3 on 2026-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_user_google_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
